// Generated by BUCKLESCRIPT VERSION 4.0.18, PLEASE EDIT WITH CARE
'use strict';

var ReactDOMRe = require("reason-react/src/ReactDOMRe.js");
var ReasonReact = require("reason-react/src/ReasonReact.js");
var Top$TodoReason = require("./Top.bs.js");

ReactDOMRe.renderToElementWithClassName(ReasonReact.element(undefined, undefined, Top$TodoReason.make(/* array */[])), "todoapp");

/*  Not a pure module */
