// Generated by BUCKLESCRIPT VERSION 4.0.18, PLEASE EDIT WITH CARE
'use strict';

var Curry = require("bs-platform/lib/js/curry.js");
var React = require("react");
var $$String = require("bs-platform/lib/js/string.js");
var ReasonReact = require("reason-react/src/ReasonReact.js");

var component = ReasonReact.statelessComponent("TodoItem");

function make(todo, onToggle, onDestroy, _children) {
  return /* record */[
          /* debugName */component[/* debugName */0],
          /* reactClassInternal */component[/* reactClassInternal */1],
          /* handedOffState */component[/* handedOffState */2],
          /* willReceiveProps */component[/* willReceiveProps */3],
          /* didMount */component[/* didMount */4],
          /* didUpdate */component[/* didUpdate */5],
          /* willUnmount */component[/* willUnmount */6],
          /* willUpdate */component[/* willUpdate */7],
          /* shouldUpdate */component[/* shouldUpdate */8],
          /* render */(function (_self) {
              var match = todo[/* completed */2];
              var className = $$String.concat(" ", /* :: */[
                    match ? "completed" : "",
                    /* [] */0
                  ]);
              return React.createElement("li", {
                          className: className
                        }, React.createElement("div", {
                              className: "view"
                            }, React.createElement("input", {
                                  className: "toggle",
                                  checked: todo[/* completed */2],
                                  type: "checkbox",
                                  onChange: (function (param) {
                                      return Curry._1(onToggle, /* () */0);
                                    })
                                }), React.createElement("label", undefined, todo[/* text */1]), React.createElement("button", {
                                  className: "destroy",
                                  onClick: (function (param) {
                                      return Curry._1(onDestroy, /* () */0);
                                    })
                                })));
            }),
          /* initialState */component[/* initialState */10],
          /* retainedProps */component[/* retainedProps */11],
          /* reducer */component[/* reducer */12],
          /* jsElementWrapped */component[/* jsElementWrapped */13]
        ];
}

exports.component = component;
exports.make = make;
/* component Not a pure module */
